backend:
  name: git-gateway
  repo: clevyoung/heeyoung-dev
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
        }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: slug, label: Slug, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: readTime, label: ReadTime, widget: number }
      - { name: body, label: Body, widget: markdown }
